function [cim_x cim_y]=SelectPixelsBack(image, p)
% image = chemin de l'image
% p = la distance (en %) par rapport au centre de l'image
% cim = imagette
I=imread(image);
[M N O]=size(I);
% M = Largeur
% N = Longueur
% O = nb de plan
minx = floor((M-p*M)/2);
miny = floor((N-p*N)/2);
maxx= minx+ floor(p*M);
maxy= miny+ floor(p*N);
cim1 = I(:,1:miny,:);
cim2 = I(:,maxy:N-1,:);
cim3 = I(1:minx,miny:maxy,:);
cim4 = I(maxx:M-1,miny:maxy,:);

cim_x= [cim1 cim2];
cim_y = [cim3 cim4];
